apiVersion: v1
kind: Pod
metadata:
  name : my-cm-pod
spec:
  containers:
  - name : myapp
    image: busybox
    command: ['sh', '-c', "echo $(MY_VAR) && sleep 3600"]
    env:
    - name: MY_VAR
      valueFrom:
        configMapKeyRef:
          name: my-config-app
          key: myKey
